provegypt/expressions/urls.py
from django.urls import path
from . import views


app_name = 'expressions'

urlpatterns = [
    path('', views.index, name="index"),
]

provegypt/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

provegypt/provegypt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('proverbe/', include('proverbe.urls')),
    path('api/', include('proverbe.api_urls')),
    path('expressions/', include('expressions.urls')),
    path('recherche/', include('recherche.urls')),
    path('', include('main.urls')),

]

provegypt/proverbe/urls.py
from django.urls import path
from . import views


app_name = 'proverbe'

urlpatterns = [
    path('', views.index, name="index"),

]

provegypt/recherche/urls.py
from django.urls import path, include
from . import views


app_name = 'recherche'

urlpatterns = [
    path('', views.index, name="index"),
    path('', include('proverbe.urls', 'expressions.urls')),
]

provegypt/expressions/models.py
from django.db import models


class Expression(models.Model):
    version_ar = models.CharField(max_length=1000)
    version_fra = models.CharField(max_length=1000)
    populaire = models.BooleanField(default=False)
    explication = models.CharField(max_length=1000)
    nom = models.CharField(max_length=100, default='test')

    def __str__(self):
        return self.nom



# Create your models here.

provegypt/main/models.py
from django.db import models

# Create your models here.

provegypt/proverbe/models.py
from django.db import models


class Proverbe(models.Model):
    version_ar = models.CharField(max_length=1000)
    version_fra = models.CharField(max_length=1000)
    populaire = models.BooleanField(default=False)
    explication = models.CharField(max_length=1000)
    nom = models.CharField(max_length=100, default='test')

    def __str__(self):
        return self.nom



# Create your models here.

provegypt/recherche/models.py
from django.db import models


class Recherche(models.Model):
    version_ar = models.CharField(max_length=1000)
    version_fra = models.CharField(max_length=1000)
    populaire = models.BooleanField(default=False)
    explication = models.CharField(max_length=1000)
    nom = models.CharField(max_length=100, default='test')

    def __str__(self):
        return self.nom



# Create your models here.
from django.db import models

# Create your models here.

provegypt/expressions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Expression
# Create your views here.


# / expression
def index(request):
    '''proverbes = Proverbe.objects.all()
    proverbes_names_and_versions = [proverbe.nom + " - VAR : " + proverbe.version_ar +
                       " - VFRA : " + proverbe.version_fra for proverbe in proverbes]
    proverbes_names_and_versions_str = ", ".join(proverbes_names_and_versions)
    return HttpResponse("Les proverbes et expressions : " + proverbes_names_and_versions_str)'''
    expressions = Expression.objects.all().order_by('nom')
    return render(request, 'expressions/index.html', {'expressions': expressions})

provegypt/main/views.py
from django.shortcuts import render
#from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, 'main/index.html')

provegypt/proverbe/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Proverbe
# Create your views here.


# / proverbe
def index(request):
    '''proverbes = Proverbe.objects.all()
    proverbes_names_and_versions = [proverbe.nom + " - VAR : " + proverbe.version_ar +
                       " - VFRA : " + proverbe.version_fra for proverbe in proverbes]
    proverbes_names_and_versions_str = ", ".join(proverbes_names_and_versions)
    return HttpResponse("Les proverbes et expressions : " + proverbes_names_and_versions_str)'''
    proverbes = Proverbe.objects.all().order_by('nom')
    return render(request, 'proverbe/index.html', {'proverbes': proverbes})


def api_get_proverbes(request):
    proverbes = Proverbe.objects.all().order_by('nom')
    json = serializers.serialize("json", proverbes)
    return HttpResponse(json)

provegypt/recherche/views.py
import cgitb

from django.shortcuts import render
from django.db.models import Q
from django.http import HttpResponse
from .models import Recherche
# Create your views here.


# / Recherche
def index(request):
    '''proverbes = Proverbe.objects.all()
    proverbes_names_and_versions = [proverbe.nom + " - VAR : " + proverbe.version_ar +
                       " - VFRA : " + proverbe.version_fra for proverbe in proverbes]
    proverbes_names_and_versions_str = ", ".join(proverbes_names_and_versions)
    return HttpResponse("Les proverbes et expressions : " + proverbes_names_and_versions_str)'''
    if 'q' in request.GET:
        q = request.GET['q']
        # recherche = Recherche.objects.filter(version_fra__icontains=q)
        multiple_q = Q(Q(version_fra__icontains=q) | Q(version_ar__icontains=q))
        recherche = Recherche.objects.filter(multiple_q)
    else:
        recherche = Recherche.objects.all().order_by('nom')
    return render(request, 'recherche/index.html', {'recherches': recherche})

provegypt/expressions/templates/expressions/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'expressions/style.css' %}">
    <title>Expressions</title>
</head>
<body>

    <div class="second-page-contenu" >
        <div class="navMenu">
            <a href="{% url 'main:index' %}">Accueil <br>صفحة رئيسية</a>
            <a href="{% url 'proverbe:index' %}">Proverbe <br> أمثال</a>
            <a href="{% url 'recherche:index' %}">Recherche <br>بحث </a>
            <a href="mailto:alexisdsc@hotmail.com?subject=Contact%20depuis%20baume%20d'Egypte">
                <!--<img id="contact" src="{% static 'proverbe/images/contact.png' %}" border="white">-->
                Contact<br>اتصال </a>
            <div class="dot"></div>
        </div>
    </div>

    <div class="title-page-secondaire">
        <h1>Expressions - أقوال</h1>
        <div class="proverbes-list">
            {% for expression in expressions %}
                <div class="expressions-list-item"> <b>{{expression.version_ar}}</b> <br> {{expression.version_fra}} </div>
                <div class="expressions-list-explain">{{expression.explication}}</div>
                {% if expression.populaire %}
                    <div class="expressions-list-badge"><i>(pop.)</i></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</body>
</html>

provegypt/main/templates/main/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <title>Baumes d'Egypte</title>
</head>

<body>
    <div class="contenu">

        <div class="normal">
            <div class="text">Baumes d'Egypte </div>
        </div>
        <div class="hover">
            <div class="text">عبق مصر</div>
        </div>

        <nav class="navMenu">
            <a href="{% url 'proverbe:index' %}">Proverbes <br>أمثال</a>
            <a href="{% url 'expressions:index' %}">Expressions <br> أقوال</a>
            <a href="{% url 'recherche:index' %}">Recherche <br>بحث </a>
            <a href="mailto:alexisdsc@hotmail.com?subject=Contact%20depuis%20baume%20d'Egypte">Contact <br>اتصال </a>
            <div class="dot"></div>
        </nav>

    </div>

</body>

</html>

provegypt/proverbe/templates/proverbe/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'proverbe/style.css' %}">
    <title>Proverbes</title>
</head>
<body>

    <div class="second-page-contenu" >
        <div class="navMenu">
            <a href="{% url 'main:index' %}">Accueil <br>صفحة رئيسية</a>
            <a href="{% url 'expressions:index' %}">Expressions <br> أقوال</a>
            <a href="{% url 'recherche:index' %}">Recherche <br>بحث </a>
            <a href="mailto:alexisdsc@hotmail.com?subject=Contact%20depuis%20baume%20d'Egypte">
                <!--<img id="contact" src="{% static 'proverbe/images/contact.png' %}" border="white">-->
                Contact<br>اتصال </a>
            <div class="dot"></div>
        </div>
    </div>

    <div class="title-page-secondaire">
        <h1>Proverbes - أمثال</h1>
        <div class="proverbes-list">
            {% for proverbe in proverbes %}
                <div class="proverbes-list-item"> <b>{{proverbe.version_ar}}</b> <br> {{proverbe.version_fra}} </div>
                <div class="proverbes-list-explain">{{proverbe.explication}}</div>
                {% if proverbe.populaire %}
                    <div class="proverbes-list-badge"><i>(pop.)</i></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</body>
</html>

provegypt/recherche/templates/recherche/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recherche/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <title>Recherche</title>
</head>
<body>
    <div class="second-page-contenu" >
        <div class="navMenu">
            <a href="{% url 'main:index' %}">Accueil <br>صفحة رئيسية</a>
            <a href="{% url 'proverbe:index' %}">Proverbe <br> أمتال</a>
            <a href="{% url 'expressions:index' %}">Expressions <br>أقوال </a>
            <a href="mailto:alexisdsc@hotmail.com?subject=Contact%20depuis%20baume%20d'Egypte">
                <!--<img id="contact" src="{% static 'proverbe/images/contact.png' %}" border="white">-->
                Contact<br>اتصال </a>
            <div class="dot"></div>
        </div>
    </div>



    <div class="wrapper">
        <div class="search_box">
            <!--<form name="search" action="¬/cgi-bin/query.py" method="get"> methode = "get" par défaut-->
            <form name="search" method="get">
                <input type="search" id="searching" name="q" placeholder="Rechercher..." aria-label="Search">
                <!--<input type="button" value="OK">-->
                <button type="submit" class="fas fa-search"></button>
            </form>
        </div>
    </div>
</body>
</html>